Django_Project_ecommerce_website/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , views.homepage , name = 'homepage'),
    path('contact/',views.contact , name = 'contact'),
    path('electronic/',views.electronic , name = 'electronic'),
    path('about-us/',views.about , name = 'about-us'),
    path('prodectdetals/',views.prodectdetals , name = 'prodectdetals'),
    path('category/',views.category , name = 'category'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)
    

homeapp/models.py
from django.db import models

class Category(models.Model):
    category_name = models.CharField(max_length=20)

    def __str__(self):
        return self.category_name
    
class Fashion(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    item_name = models.CharField(max_length=20)
    price = models.DecimalField(max_digits=5, decimal_places=2, default=None)
    item_img = models.ImageField(upload_to='homepage', max_length=100, null=True, default=None)

    def __str__(self):
        return self.item_name
 

Django_Project_ecommerce_website/views.py
from django.shortcuts import render
from homeapp.models import Category , Fashion 
from django.core.paginator import Paginator

global_data = None

def paginator_function(data , show , request ):
    paginator = Paginator(data , show)
    page_num = request.GET.get('page')
    f_data = paginator.get_page(page_num)
    total_page = f_data.paginator.num_pages
    return { 'f_data': f_data , 'total_page' : total_page} 
    
def homepage(request):
    category_items = Category.objects.all().order_by('category_name')
    fashion_data_n = Fashion.objects.all().order_by('item_name')
    fashion_data = paginator_function(fashion_data_n, 3, request)
    total_page = fashion_data['total_page']
    fashion_data = fashion_data['f_data']
    
    data = {
         'fashion_data' : fashion_data , 'total_page' : total_page , 
          'category_items' : category_items ,
          }

    return render(request , 'homepage.html' , data)





def contact(request):
    return render(request , 'contact.html')
    
def electronic(request):
     return render(request , 'electronic.html')
    
def about(request):
     return render(request , 'about-us.html')
    
def prodectdetals(request):
     return render(request , 'prodectdetals.html')
    
def category(request):
    category_items = Category.objects.all().order_by('category_name')
    fashion_data = Fashion.objects.all().order_by('item_name')
    
    data = {
         'fashion_data' : fashion_data , 
          'category_items' : category_items ,
          }

    return render(request , 'category.html' , data)

homeapp/views.py
from django.shortcuts import render

# Create your views here.

templates/about-us.html
{% extends 'base.html'%}
{% block content %}


<!-- About Us Content -->
<div class="container mt-4">
    <div class="row">
        <div class="col-lg-6">
            <h2>About Us</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse
                malesuada lacus ex, sit amet blandit leo lobortis eget.
            </p>
        </div>
       
    </div>


<!-- Additional Content or Sections -->
<!-- Additional Sections -->
<div class="row mt-4">
    <div class="col-lg-6">
        <h3>Our Mission</h3>
        <p>
            Our mission is to provide high-quality products and services to our
            customers while maintaining a commitment to sustainability and social
            responsibility.
        </p>
    </div>
    <div class="col-lg-6">
        <h3>Our Team</h3>
        <p>
            Meet our dedicated team of experts who work tirelessly to ensure the
            success of our company and the satisfaction of our customers.
        </p>
    </div>
</div>

</div>
</div>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

{% endblock%}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="viewport" content="initial-scale=1, maximum-scale=1" />
    <!-- site metas -->
    <title>E-Commerce {% block title %} {% endblock %}</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- bootstrap css -->
    <link rel="stylesheet" type="text/css" href={% static  'css/bootstrap.min.css' %} />
    <!-- style css -->
    <link rel="stylesheet" type="text/css" href={% static 'css/style.css' %} />
    <!-- Responsive-->
    <link rel="stylesheet" href={% static 'css/responsive.css' %}/>
    
    <!-- fevicon -->
    <link rel="icon" href={% static 'images/fevicon.png' %} type="image/gif" />
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href={% static '/css/jquery.mCustomScrollbar.min.css' %} />
    <!-- Tweaks for older IEs-->
    <link
      rel="stylesheet"
      href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css"
    />
    <!-- fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap"
      rel="stylesheet"
    />
    <!-- font awesome -->
    
    <link
      rel="stylesheet"
      type="text/css"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <!--  -->
    <!-- owl stylesheets -->
    <link
      href="https://fonts.googleapis.com/css?family=Great+Vibes|Poppins:400,700&display=swap&subset=latin-ext"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="/static/css/owl.carousel.min.css" />
    <link rel="stylesoeet" href="/static/css/owl.theme.default.min.css" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
      media="screen"
    />
  </head>
  <body>
    <!--  banner bg main start -->
    <div class="banner_bg_main">
      <!-- header top section start -->
      <div class="container">
        <div class="header_section_top">
          <div class="row">
            <div class="col-sm-12">
              <div class="custom_menu">
                <ul>
                  <li><a href="#">Best Sellers</a></li>
                  <li><a href="#">Gift Ideas</a></li>
                  <li><a href="#">New Releases</a></li>
                  <li><a href="#">Today's Deals</a></li>
                  <li><a href={% url 'contact'%}>Customer Service</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- header top section start -->
      <!-- logo section start -->
      <div class="logo_section">
        <div class="container">
          <div class="row">
            <div class="col-sm-12">
              <div class="logo">
                <a href={% url 'homepage' %}><img src="/static/images/logo.png" /></a>
              </div>
            </div>
          </div>
        </div>

      </div>
      <!-- logo section  end -->
      <!-- header section start -->
      <div class="header_section">
        <div class="container">
          <div class="containt_main">
            <div id="mySidenav" class="sidenav">
              <a href="javascript:void(0)" class="closebtn" onclick="closeNav()"
                >&times;</a
              >
              <a href={% url 'homepage' %}>Home</a>
              <a href={% url 'about-us' %}>About US</a>
              <a href={% url 'contact' %}>Contact US</a>
              {%for n in  category_items %}
                <a href="">{{n.category_name}}</a>
                {% endfor%}
              
            </div>
            <span class="toggle_icon" onclick="openNav()"
              ><img src="/static/images/toggle-icon.png"
            /></span>
            <div class="dropdown">
              <button
                class="btn btn-secondary dropdown-toggle"
                type="button"
                id="dropdownMenuButton"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                All Category
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                {%for n in  category_items%}
                <a class="dropdown-item" href="">{{n.category_name}}</a>
                {% endfor%}
              </div>
            </div>
            <div class="main">
              <!-- Another variation with a button -->
              <div class="input-group">
                <input type="text"  class="form-control" placeholder="Search this blog" />
                <div class="input-group-append">
                  <button  class="btn btn-secondary" type="button" style="background-color: #f26522; border-color: #f26522">
                    <i class="fa fa-search"></i>
                  </button>
                </div>
              </div>
            </div>
            <div class="header_box">
              <div class="login_menu">
                <ul>
                  <li>
                    <a href="#">
                      <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                      <span class="padding_10">Cart</span></a
                    >
                  </li>
                  <li>
                    <a href="#">
                      <i class="fa fa-list" aria-hidden="true"></i>
                      <span class="padding_10">List</span></a
                    >
                  </li>
                  <li>
                    <a href="#">
                      <i class="fa fa-user" aria-hidden="true"></i>
                      <span class="padding_10">Login</span></a
                    >
                  </li>
                  <li>
                    <a href="#">
                      <i class="fa fa-user" aria-hidden="true"></i>
                      <span class="padding_10">Sign Up</span></a
                    >
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- header section end -->
    </body>
    </html>
    
{% block content %}


{% endblock %}


<!-- footer section start -->
<div class="footer_section layout_padding">
    <div class="container">
      <div class= "col-lg-6">
        <a href="{% url 'homepage' %}">
          <img src="/static/images/logo.png" class="img-fluid" alt="Company Image">

         </a>
      </div>
      <div class="input_bt">
        <input
          type="text"
          class="mail_bt"
          placeholder="Your Email"
          name="Your Email"
        />
        <span class="subscribe_bt" id="basic-addon2"
          ><a href="#">Subscribe</a></span
        >
      </div>
      <div class="footer_menu">
        <ul>
          <li><a href="#">Best Sellers</a></li>
          <li><a href="#">Gift Ideas</a></li>
          <li><a href="#">New Releases</a></li>
          <li><a href="#">Today's Deals</a></li>
          <li><a href={% url 'contact' %}>Customer Service</a></li>
        </ul>
      </div>
      <div class="location_main">
        Help Line Number : <a href="#">+1 1800 1200 1200</a>
      </div>
    </div>
  </div>
  <!-- footer section end -->
  <!-- copyright section start -->
  <div class="copyright_section">
    <div class="container">
      <p class="copyright_text">
        © 2023 All Rights Reserved. Design by
        <a href="https://ashok-prajapati2.github.io/project-resume/">ASHOK KUMAR</a>
      </p>
    </div>
  </div>
  <!-- copyright section end -->
  <!-- Javascript files-->
  <script src="/static/js/jquery.min.js"></script>
  <script src="/static/js/bootstrap.bundle.min.js"></script>
  <script src="/static/js/jquery-3.0.0.min.js"></script>
  <script src="/static/js/plugin.js"></script>
  <script src="/static/js/popper.min.js"></script>
  <!-- sidebar -->
  <script src="/static/js/jquery.mCustomScrollbar.concat.min.js"></script>
  <script src="/static/js/custom.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  
  <script>
    function openNav() {
      document.getElementById("mySidenav").style.width = "250px";
    }

    function closeNav() {
      document.getElementById("mySidenav").style.width = "0";
    }
  </script>

templates/category.html
{% extends 'base.html' %} 
{% block title %}category{% endblock %}
{% block content %}

<div class="grid text-center">
    {% for category_item in category_items %}
    <div class="g-col-6 g-col-md-4">
        <div class="container">
            <h1 class="fashion_taital">{{ category_item }}</h1>
          
            <div class="row">
              {% for fashion_item in category_item.fashion_set.all %}
                <div class="col-lg-4 col-md-6 col-sm-12">
                  <div class="box_main mb-4">
                    <h4 class="shirt_text">{{ fashion_item.item_name }}</h4>
                    <p class="price_text">
                      Price <span class="text-dark">$ {{ fashion_item.price }}</span>
                    </p>
                    <div class="tshirt_img">
                      <img src="/media/{{ fashion_item.item_img }}" class="img-fluid" />
                    </div>
                    <div class="btn_main mt-3">
                      <div class="buy_bt"><a href="#" class="btn btn-primary">Buy Now</a></div>
                      <div class="seemore_bt"><a href="#" class="btn btn-secondary">See More</a></div>
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>
          </div>

  {% endfor %}
</div>

{% endblock %}

templates/contact.html
{%extends 'base.html' %}

{% block content %}

   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<style>
   
  .mt-4{
   color: gray;
  }
  .container{
    margin-bottom: 50px;
  }
  .top-margin {
    margin-top: 100px;
}
</style>

<div class="container top-margin">
   <div class="row">
       <div class="col-lg-6 offset-lg-3">
           <h1 class="text-center mt-4">Get In Touch</h1>
           <form>
               <div class="form-group">
                   <input type="text" class="form-control" placeholder="Name">
               </div>
               <div class="form-group">
                   <input type="text" class="form-control" placeholder="Phone Number">
               </div>
               <div class="form-group">
                   <input type="email" class="form-control" placeholder="Email">
               </div>
               <div class="form-group">
                   <textarea class="form-control" placeholder="Message" rows="5"></textarea>
               </div>
               <button type="submit" class="btn btn-primary btn-block">Send</button>
           </form>
       </div>
   </div>
</div>




<!-- Additional content or styling can be added here -->

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

 <!-- contact section end -->
 {% endblock  %}

templates/electronic.html
{% extends 'base.html' %}
{% block content %}
         <!-- banner section start -->
         <div class="banner_section layout_padding">
            <div class="container">
               <div id="my_slider" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner">
                     <div class="carousel-item active">
                        <div class="row">
                           <div class="col-sm-12">
                              <h1 class="banner_taital">Get Start <br>Your favriot shoping</h1>
                              <div class="buynow_bt"><a href="#">Buy Now</a></div>
                           </div>
                        </div>
                     </div>
                     <div class="carousel-item">
                        <div class="row">
                           <div class="col-sm-12">
                              <h1 class="banner_taital">Get Start <br>Your favriot shoping</h1>
                              <div class="buynow_bt"><a href="#">Buy Now</a></div>
                           </div>
                        </div>
                     </div>
                     <div class="carousel-item">
                        <div class="row">
                           <div class="col-sm-12">
                              <h1 class="banner_taital">Get Start <br>Your favriot shoping</h1>
                              <div class="buynow_bt"><a href="#">Buy Now</a></div>
                           </div>
                        </div>
                     </div>
                  </div>
                  <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
                  <i class="fa fa-angle-left"></i>
                  </a>
                  <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
                  <i class="fa fa-angle-right"></i>
                  </a>
               </div>
            </div>
         </div>
         <!-- banner section end -->
      </div>
      <!-- banner bg main end -->
      <!-- electronic section start -->
      <div class="fashion_section">
         <div id="electronic_main_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
               <div class="carousel-item active">
                  <div class="container">
                     <h1 class="fashion_taital">Electronic</h1>
                     <div class="fashion_section_2">
                        <div class="row">
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">Laptop</h4>
                                 <p class="price_text">Start Price  <span style="color: #262626;">$ 100</span></p>
                                 <div class="electronic_img"><img src="images/laptop-img.png"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="#">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="#">See More</a></div>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">Mobile</h4>
                                 <p class="price_text">Start Price  <span style="color: #262626;">$ 100</span></p>
                                 <div class="electronic_img"><img src="images/mobile-img.png"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="#">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="#">See More</a></div>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">Computers</h4>
                                 <p class="price_text">Start Price  <span style="color: #262626;">$ 100</span></p>
                                 <div class="electronic_img"><img src="images/computer-img.png"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="#">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="#">See More</a></div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="carousel-item">
                  <div class="container">
                     <h1 class="fashion_taital">Electronic</h1>
                     <div class="fashion_section_2">
                        <div class="row">
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">Laptop</h4>
                                 <p class="price_text">Start Price  <span style="color: #262626;">$ 100</span></p>
                                 <div class="electronic_img"><img src="images/laptop-img.png"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="#">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="#">See More</a></div>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">Mobile</h4>
                                 <p class="price_text">Start Price  <span style="color: #262626;">$ 100</span></p>
                                 <div class="electronic_img"><img src="images/mobile-img.png"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="#">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="#">See More</a></div>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">Computers</h4>
                                 <p class="price_text">Start Price  <span style="color: #262626;">$ 100</span></p>
                                 <div class="electronic_img"><img src="images/computer-img.png"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="#">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="#">See More</a></div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="carousel-item">
                  <div class="container">
                     <h1 class="fashion_taital">Electronic</h1>
                     <div class="fashion_section_2">
                        <div class="row">
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">Laptop</h4>
                                 <p class="price_text">Start Price  <span style="color: #262626;">$ 100</span></p>
                                 <div class="electronic_img"><img src="images/laptop-img.png"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="#">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="#">See More</a></div>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">Mobile</h4>
                                 <p class="price_text">Start Price  <span style="color: #262626;">$ 100</span></p>
                                 <div class="electronic_img"><img src="images/mobile-img.png"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="#">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="#">See More</a></div>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">Computers</h4>
                                 <p class="price_text">Start Price  <span style="color: #262626;">$ 100</span></p>
                                 <div class="electronic_img"><img src="images/computer-img.png"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="#">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="#">See More</a></div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            <a class="carousel-control-prev" href="#electronic_main_slider" role="button" data-slide="prev">
            <i class="fa fa-angle-left"></i>
            </a>
            <a class="carousel-control-next" href="#electronic_main_slider" role="button" data-slide="next">
            <i class="fa fa-angle-right"></i>
            </a>
         </div>
      </div>
      <!-- electronic section end -->
   {% endblock %}

templates/homepage.html
{%extends 'base.html' %}
{% block title %}Home{% endblock %}
{%block content %}
<style>
  .col-sm-12 h1 img{
    width: 80px;
  }
</style>
<section>
      <!-- banner section start -->
      <div class="banner_section layout_padding">
        <div class="container">
          <div id="my_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
             {% for n in fashion_data %}
              <div class="carousel-item {% if forloop.first %}active{% endif %}">
                <div class="row">
                  <div class="col-sm-12">
                    <h1 class="banner_taital"> {{n.item_name}} <br /> <img src="/media/{{n.item_img}}" /><br/>
                      <p class="price_text"> Price <span style="color: #262626">$ {{n.price}}</span> </p>
                    </h1>
                    <div class="buynow_bt"><a href="">Buy Now</a></div>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#my_slider" role="button"  data-slide="prev"><i class="fa fa-angle-left"></i></a>
            <a class="carousel-control-next"  href="#my_slider" role="button" data-slide="next"><i class="fa fa-angle-right"></i></a>
          </div>
        </div>
      </div>
      <!-- banner section end -->
    </div>
    <!-- banner bg main end -->
<!-- fashion section start -->
{% for category_item in category_items %}
  <div class="fashion_section">
   <div id="main_slider" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
            <div class="container">
               <h1 class="fashion_taital">{{ category_item.category_name }}</h1>
               <div class="fashion_section_2">
                  <div class="row">
                     {% for fashion_item in category_item.fashion_set.all %}
                     <div class="col-lg-4 col-sm-4">
                        <div class="box_main">
                           <h4 class="shirt_text">{{ fashion_item.item_name }}</h4>
                           <p class="price_text">Price  <span style="color: #262626;">$ {{ fashion_item.price }}</span></p>
                           <div class="tshirt_img"><img src=" /media/{{fashion_item.item_img}} "></div>
                           <div class="btn_main">
                              <div class="buy_bt"><a href="#">Buy Now</a></div>
                              <div class="seemore_bt"><a href="#">See More</a></div>
                           </div>
                        </div>
                     </div>
                     {% endfor %}
                  </div>
               </div>
            </div>
           </div>
      </div>
   <div class="d-flex justify-content-center align-items-center" style="padding-bottom: 100px">
        <nav aria-label="...">
          <ul class="pagination">
          {% if fashion_data.has_previous %}
            <li class="page-item "> <a class="page-link" href="?page=1">First</a>  </li>
            <li class="page-item">  <a class="page-link" href="?page={{ fashion_data.previous_page_number }}">Previous</a> </li>
           {% endif %}
          {% for n in fashion_data.paginator.page_range %}
            <li class="page-item {% if n == fashion_data.number %}active{% endif %}"> <a class="page-link" href="?page={{n }}">{{ n }}</a></li>
          {% endfor %}
           
        {% if fashion_data.has_next %}
        <li class="page-item"> <a class="page-link" href="?page={{ fashion_data.next_page_number }}">Next</a> </li>
        <li class="page-item">  <a class="page-link" href="?page={{ fashion_data.paginator.num_pages }}">Last</a> </li>
        {% endif %}
         </ul>
        </nav> 
    </div>
  </div>
</div>
{% endfor %}
<!-- fashion section end -->
</section>
{% endblock %}